### ISSUE TITLE
await till database is clean

### ISSUE THREAD

**Issue by handmilkingsoftware** [talyssonoc/node-api-boilerplate#18]
I have a problem and is that the clean database script just returns the promise and the caller doesn't wait for it

it should look like:

```
beforeEach(async() => {
  await cleanDatabase();
});
```

I'm not using sequelizejs though, I adapted it to knex but I just checked sequelizejs documentation and it tructate returns a promise indeed.

**Comment by talyssonoc** [comment]
The way it is right now the `beforeEach` should wait for the promise to be resolved since I return it from the function (https://github.com/talyssonoc/node-api-boilerplate/blob/master/test/support/cleanDatabase.js#L4). It is similar to returning a promise from an `it`, Mocha waits for it to be resolved.  `await`ing a promise inside an `async` function works exactly the same as returning a promise from a normal function.
