### ISSUE TITLE
Folders structure

### ISSUE THREAD

**Issue by duard** [talyssonoc/node-api-boilerplate#28]
I think the folders structure is very complicated / confusing ...

Would be better resources folders, like : 

https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md

users
products
vehicles
...
etc

thanks for share this project.

**Comment by talyssonoc** [comment]
Hey, @duard. Actually I do organize the folders in resources (I prefer to call them concepts) but I also separate each [layer](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/createlayers.md) in its own folder instead of everything related to a given concept inside the same folder.

Leaving everything related to a concept in the same folder can lead to two possible outcomes: 1) end up with a unorganized folder full of non-related files beside each other (like a database model, an entity and a controller all in the same folder), or 2) end up organizing the folder of each concept/resource by [technical role](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/thincomponents.md#bad-group-your-files-by-technical-role), which is worse.

So that's why I prefer to separate into layers and then each layer into concepts/resources.

You can read more about why I organized it this way in [this blog post of mine](https://blog.codeminer42.com/nodejs-and-good-practices-354e7d763626) or in this repo [wiki](https://github.com/talyssonoc/node-api-boilerplate/wiki/Folder-structure).

**Comment by duard** [comment]
I will read, thanks man.
