### ISSUE TITLE
Injecting Domain models

### ISSUE THREAD

**Issue by aarontropy** [talyssonoc/node-api-boilerplate#29]
Great project!  I literally study the code.

Question: Why not inject your domain entities via awilix?  UserRepository grabs the User entity via `require()`

**Comment by talyssonoc** [comment]
Thanks @aarontropy!

The reason why I don't inject it is mostly semantic: I don't consider the domain entity an dependency of the repository, what happens is that the repository creates instances of entities instead of depending on them. But anyway there's nothing wrong in injecting them if needed/wanted :smile:
