### ISSUE TITLE
Why do not move serialization function to domain model class?

### ISSUE THREAD

**Issue by massimo-ua** [talyssonoc/node-api-boilerplate#37]
I mean if User class would have method to serialize itself then you don't need to have special UserSerializer function separately and serialization setup in that case will be more transparent (because it will be made in the same place as model definition). So you can define public and protected properties of model and serialize only public properties for example

**Comment by talyssonoc** [comment]
It's because it's not domain's responsibility to serialize an entity as it's entry-point-bound. For example, you could have two entry points: the REST API and the GraphQL API and have a different serialization in schema for each of team. Both the REST and GraphQL part receive the same user as response from the use case and it's up to them to serialize it based in what their clients expect.

**Comment by massimo-ua** [comment]
Ok. Concept is really clear. Thanks for the reply
