### ISSUE TITLE
Complete tutorial please for the best practice of PUT, DESTROY, and SHOW methods ?

### ISSUE THREAD

**Issue by fatkhanfauzi** [talyssonoc/node-api-boilerplate#7]
could you please provide examples for PUT, DESTROY, SHOW ?

also adding below features would be great.
- library to return json as json api standard (i'm using serializer for now)
- proper error handling with return http code

**Comment by talyssonoc** [comment]
@fatkhanfauzi O like the idea of adding examples for PUT, DESTOY and SHOW, gonna work on that soon :)

I think proper error handling would be good too, I added that in a project I used this boilerplate, I may copy the ideas from there and use it here. But I don't like the idea of adding a library to set the default response format as JSON API standard, most JSON APIs don't use it since it's too strict some times and it's also pretty easy to add it if need  with this lib http://npmjs.com/package/jsonapi-serializer (I believe it's the one you're using).

**Comment by fatkhanfauzi** [comment]
thanks for your response.
I have created PUT, DESTROY, and SHOW method here https://github.com/fatkhanfauzi/node-api-boilerplate/tree/feature/complete_user_crud

but i'm also using http://npmjs.com/package/jsonapi-serializer on it.

**Comment by talyssonoc** [comment]
Thanks @fatkhanfauzi!
